[project]
name = "dotfiles"
version = "0.1.0"
description = "Add a short description here"
authors = ["Steven Eisinger <seisinger@smart-robotics.nl>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
bat = ">=0.24.0,<0.25"
tmux = ">=3.4,<4"
starship = ">=1.18.1,<1.19"
go-shfmt = ">=3.8.0,<3.9"
ripgrep = ">=14.1.0,<14.2"
fd-find = ">=8.5.3,<8.6"
gh = ">=2.45.0,<2.46"
jq = ">=1.7.1,<1.8"
nnn = ">=4.7,<5"
pre-commit = ">=3.7.0,<3.8"
git-delta = ">=0.17.0,<0.18"
fzf = ">=0.48.1,<0.49"
shellcheck = ">=0.9.0,<0.10"
