[groups.laptop]
label = "Laptop KB + Trackpad"
keyboards = ["AT Translated Set 2"]
pointers = ["DELL","Synaptics", "ALPS TrackPoint"]
kill_combo = "ctrl+alt+shift+k"
wake_combo = "ctrl+alt+shift+w"
virtual = false
