# Author: Steven Eisinger <steven.a.eisinger@gmail.com>

#
# prompt common
#

format = """
[ [\uE0B6](cyan)$username$hostname$singularity$directory[\uE0B8](cyan)[\uE0BE](yellow)$vcsh$git_branch$git_commit$git_state$git_metrics$git_status$hg_branch[\uE0B4](yellow) $all$fill[\uE0B6](yellow)$jobs[\uE0BC](yellow)[\uE0BA](purple)$time[\uE0B4](purple) ](dimmed white)
$character"""

[fill]
symbol = " "
style = "dimmed white"

[line_break]
disabled = true

[cmd_duration]
disabled = true

[cmake]
disabled = true

[battery]
disabled = true

[shell]
disabled = true

#
# left prompt - dir and user
#

[username]
show_always = false
format = "[$user](fg:$style bg:cyan)[█](cyan)"
style_root = "bold red"
style_user = "bold white"

[hostname]
ssh_only = true
format = "[@$hostname](fg:bold white bg:$style)[█]($style)"
style = "cyan"

[singularity]
format = '[\[$env\]](fg:bold white bg:$style)[█]($style)'
style = "cyan"

[directory]
format = "[$read_only$path](bold fg:white bg:$style)[█]($style)"
read_only = " "
read_only_style = "bold fg:white bg:$style"
style = "cyan"
truncation_symbol = "…/"

#
# left prompt - version control systems
#

[vcsh]
format = "[$symbol$repo](fg:bold white bg:$style)[█]($style)"
style = "yellow"

[git_branch]
format = "[$symbol$branch](fg:bold white bg:$style)[█]($style)"
style = "yellow"

[git_commit]
format = "[\\($hash$tag\\)](fg:bold white bg:$style)[█]($style)"
style = "yellow"

[git_state]
format = '\([$state( $progress_current/$progress_total)](fg:bold white bg:$style)\)[█]($style)'
style = "yellow"

[git_metrics]

[git_status]
format = '[\[$all_status$ahead_behind\]](fg:bold red bg:$style)[█]($style)'
style = "yellow"

[hg_branch]
format = "[$symbol$branch](fg:bold white bg:$style)[█]($style)"
style = "yellow"
disabled = false

#
# right prompt - jobs
#

[jobs]
format = "[█]($style)[$symbol$number](fg:bold white bg:$style)"
style = "yellow"

#
# right prompt - time
#

[time]
disabled = false
format = "[█]($style)[$time](fg:bold white bg:$style)"
style = "purple"

#
# second line - character prompt
#

[character]
success_symbol = "[\uE0B0](dimmed white)"
error_symbol = "[\uE0B0](red)"
vicmd_symbol = "[\uE0B1](dimmed white)"
