# Author: Steven Eisinger <steven.a.eisinger@gmail.com>

#
# prompt common
#

format = """
[[█](cyan)$username$hostname$singularity$directory$vcsh$git_branch$git_commit$git_state$git_metrics$git_status$hg_branch$fill\uE0B7 $all\uE0B5$fill$jobs$time](dimmed white)
$character"""

[fill]
symbol = "─"
style = "dimmed white"

[line_break]
disabled = true

[cmd_duration]
disabled = true

[cmake]
disabled = true

[battery]
disabled = true

[shell]
disabled = true

#
# left prompt - dir and user
#

[username]
show_always = false
format = "[$user](fg:$style bg:cyan)[█](cyan)"
style_root = "bold red"
style_user = "bold white"

[hostname]
ssh_only = true
format = "[@$hostname](fg:bold white bg:$style)[█]($style)"
style = "cyan"

[singularity]
format = '[\[$env\]](fg:bold white bg:$style)[█]($style)'
style = "cyan"

[directory]
format = "[$read_only$path](bold fg:white bg:$style)[█]($style)"
read_only = " "
read_only_style = "bold fg:white bg:$style"
style = "cyan"
truncation_symbol = "…/"

#
# left prompt - version control systems
#

[vcsh]

[git_branch]
format = "[█]($style)[$symbol$branch](fg:bold white bg:$style)[█]($style)"
style = "green"

[git_commit]
format = "[\\($hash$tag\\)](fg:bold white bg:$style)[█]($style)"
style = "green"

[git_state]
format = '\([$state( $progress_current/$progress_total)](fg:bold white bg:$style)\)[█]($style)'
style = "green"

[git_metrics]

[git_status]
format = '[\[$all_status$ahead_behind\]](fg:bold red bg:$style)[█]($style)'
style = "green"

[hg_branch]

#
# right prompt - jobs and time
#

[jobs]

[time]
disabled = false
format = "[\uE0B6[$time](bold fg:white bg:$style)█]($style)"
style = "purple"

#
# second line - character prompt
#

[character]
success_symbol = "[\uE0B0](dimmed white)"
error_symbol = "[\uE0B0](red)"
vicmd_symbol = "[\uE0B1](dimmed white)"
