#
# Daydream theme for starship prompt, featuring gruvbox material colors
#
# Authors:
#   Steven Eisinger <steven.a.eisinger@gmail.com>
#

#
# Prompt common
#

format = """
${custom.left_start}\
$username\
$hostname\
$singularity\
$directory\
${custom.left_sep}\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
${custom.left_end}\
$nix_shell\
$docker_context\
$conda\
$python\
$fill\
${custom.right_start}\
$cmd_duration\
$jobs\
${custom.right_sep}\
$time\
${custom.right_end}\
$line_break\
$character"""

[fill]
symbol = " "

#
# Left prompt 1
#

[custom.left_start]
format = " [ \uE0B6](#7daea3)"
when = "true"

[username]
show_always = false
format = "[$user](fg:$style bg:#7daea3)[█](#7daea3)"
style_root = "bold #ea6962"
style_user = "bold #282828"

[hostname]
ssh_only = true
format = "[ $hostname](fg:bold #282828 bg:$style)[█]($style)"
style = "#7daea3"

[singularity]
format = '[\[$env\]](fg:bold #282828 bg:$style)[█]($style)'
style = "#7daea3"

[directory]
format = "[$read_only$path](fg:bold #282828 bg:$style)[█]($style)"
read_only = " "
style = "#7daea3"
fish_style_pwd_dir_length = 2
truncation_length = 1

[custom.left_sep]
format = "[░▒▓](fg:#d4be98 bg:#7daea3)"
when = "true"

#
# Left prompt 2
#

[vcsh]
format = "[$symbol$repo](fg:bold #282828 bg:$style)[█]($style)"
symbol = ""
style = "#d4be98"

[git_branch]
format = "[$symbol$branch](fg:bold #282828 bg:$style)[█]($style)"
symbol = ""
style = "#d4be98"

[git_commit]
format = "[\\($hash$tag\\)](fg:bold #282828 bg:$style)[█]($style)"
style = "#d4be98"

[git_state]
format = '\([$state( $progress_current/$progress_total)](fg:bold #282828 bg:$style)\)[█]($style)'
style = "#d4be98"

[git_metrics]

[git_status]
format = '[\[$all_status$ahead_behind\]](fg:bold #282828 bg:$style)[█]($style)'
style = "#d4be98"

[hg_branch]
format = "[$symbol$branch](fg:bold #282828 bg:$style)[█]($style)"
symbol = ""
style = "#d4be98"
disabled = false

[custom.left_end]
format = "[\uE0B4](#d4be98)"
when = "true"

#
# Middle prompt
#

[nix_shell]
format = " [\uE0B6]($style)[$state(:$name)](fg:bold #d4be98 bg:$style)[\uE0B4]($style)"
style = "#665c54"

[docker_context]
format = " [\uE0B6]($style)[$context](fg:bold #7daea3 bg:$style)[\uE0B4]($style)"
style = "#665c54"

[conda]
format = " [\uE0B6]($style)[$environment](fg:bold #a9b665 bg:$style)[\uE0B4]($style)"
style = "#665c54"

[python]
format = " [\uE0B6]($style)[${pyenv_prefix}$virtualenv](fg:bold #d8a657 bg:$style)[\uE0B4]($style)"
style = "#665c54"
pyenv_prefix = "pyenv:"

#
# Right prompt 1
#

[custom.right_start]
format = "[\uE0B6](#d4be98)"
when = "true"

[cmd_duration]
format = "[█]($style)[took $duration](fg:bold #282828 bg:$style)"
style = "#d4be98"

[jobs]
format = "[█]($style)[$symbol$number](fg:bold #282828 bg:$style)"
style = "#d4be98"

[custom.right_sep]
format = "[▓▒░](fg:#d4be98 bg:#ea6962)"
when = "true"

#
# Right prompt 2
#

[time]
disabled = false
format = "[█]($style)[$time](fg:bold #282828 bg:$style)"
style = "#ea6962"

[custom.right_end]
format = "[\uE0B4 ](#ea6962)"
when = "true"

#
# Second line
#

[character]
success_symbol = "[\u25CF](#7daea3)"
error_symbol = "[\u25CF](#ea6962)"
vicmd_symbol = "[\u25CB](#7daea3)"
