#
# Custom theme for starship.rs
#
# Authors:
#   Steven Eisinger <steven.a.eisinger@gmail.com>
#

#
# Prompt common
#

format = """
[ [\uE0B6█](cyan)$username$hostname$singularity$directory[\uE0B8](cyan)[\uE0BE█](yellow)$vcsh$git_branch$git_commit$git_state$git_metrics$git_status$hg_branch[\uE0B4](yellow) [\uE0B6█](black)$nix_shell$docker_context$conda$python[\uE0B4](black)$fill[\uE0B6](yellow)$cmd_duration$jobs[█\uE0BC](yellow)[\uE0BA](purple)$time[█\uE0B4](purple) ]()
$character"""

[fill]
symbol = " "
style = "dimmed white"

#
# Left prompt 1
#

[username]
show_always = false
format = "[$user](fg:$style bg:cyan)[█](cyan)"
style_root = "bold red"
style_user = "bold white"

[hostname]
ssh_only = true
format = "[@$hostname](fg:bold white bg:$style)[█]($style)"
style = "cyan"

[singularity]
format = '[\[$env\]](fg:bold white bg:$style)[█]($style)'
style = "cyan"

[directory]
format = "[$read_only$path](fg:bold white bg:$style)[█]($style)"
read_only = " "
style = "cyan"
truncation_symbol = "…/"

#
# Left prompt 2
#

[vcsh]
format = "[$symbol$repo](fg:bold white bg:$style)[█]($style)"
style = "yellow"

[git_branch]
format = "[$symbol$branch](fg:bold white bg:$style)[█]($style)"
style = "yellow"

[git_commit]
format = "[\\($hash$tag\\)](fg:bold white bg:$style)[█]($style)"
style = "yellow"

[git_state]
format = '\([$state( $progress_current/$progress_total)](fg:bold white bg:$style)\)[█]($style)'
style = "yellow"

[git_metrics]

[git_status]
format = '[\[$all_status$ahead_behind\]](fg:bold red bg:$style)[█]($style)'
style = "yellow"

[hg_branch]
format = "[$symbol$branch](fg:bold white bg:$style)[█]($style)"
style = "yellow"
disabled = false

#
# Middle prompt
#

[nix_shell]
format = '[$state( \($name\))](fg:bold white bg:$style)[█]($style)'
style = "black"

[docker_context]
format = "[$context](fg:bold blue bg:$style)[█]($style)"
style = "black"

[conda]
format = "[$environment](fg:bold green bg:$style)[█]($style)"
style = "black"

[python]
format = "[${pyenv_prefix}$virtualenv](fg:bold yellow bg:$style)[█]($style)"
style = "black"
pyenv_prefix = "pyenv:"

#
# Right prompt 1
#

[cmd_duration]
format = "[█]($style)[took $duration](fg:bold white bg:$style)"
style = "yellow"

[jobs]
format = "[█]($style)[$symbol$number](fg:bold white bg:$style)"
style = "yellow"

#
# Right prompt 2
#

[time]
disabled = false
format = "[█]($style)[$time](fg:bold white bg:$style)"
style = "purple"

#
# Second line
#

[character]
success_symbol = "[\u25CF](cyan)"
error_symbol = "[\u25CF](red)"
vicmd_symbol = "[\u25CB](cyan)"
